language: java

cache:
  directories:
  - "$HOME/.m2"

before_install:
  - pip install --user codecov

script:
  - mvn -s settings.xml clean install

after_success:
  - codecov

branches: 
  except:
    - gh-pages

deploy:
  provider: releases
  api_key:
    - secure: UTGuUnbATvWnMDXpDXd9PCw2fn5LauJrebpPhTQ7lb/F1UD3h0E+9K7qJayUETBdovaKpUL9UtpJ/KHcXeWR490qM+OWCyYGyKHRNhTb8ssSyfwTOQvbfJOHGzKeOrIERtsG0JqI3YZWyJyycUF+azsvPwDJ1hA0b74nD798KRVkZCuZ28zv8mOL5o/JWhDQ4FS39F9CGbnbco9WtHUhLmp9PzchXewoEF+1XuXwtASpP4FPPm2Fu+scFzrFjvRePhg//pu4qGAFghHTFMm1YC45u+jc/tRfL2Uv+BAPeRUIk12f+gnEfybWdTs7Z20MbOy0m9/JabdL61AZ45sfWDFYe26D4RChSl8TeW1ZFpCvQW4sKmjdhWPwUbr67ycoa8d8/obDFt9wDFtav1FEG/9NhOzV6qZLJOHNq9OdZodkIkNp5axcrv8IJvUeBAEGkm6I4+T+Zw3xjdiORsYKxPl7FeRZ2fqL3CfuPqFdoIBJzXO9m5gZemubeAFcwMrnRZy+vCiscQiqrwUy8X47QhADnYzZd6VvU8CJwRoi+7JvdM1c8fljrfbANxXqDKTBzTOhPtEgWQ8hZ7mr20mGfcX6D28qdIhhagd+ZV+L1CTNOfXfWy5a8EDqsnJE0BE/mxW9wjx7jLIn/l+IG/MvZO9OL4uLUTLIIfbLFa3ThHM=
  file:
    - "$TRAVIS_BUILD_DIR/target/sort-descriptor-*-sources.jar"
    - "$TRAVIS_BUILD_DIR/target/sort-descriptor-*.jar"
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - mvn -s settings.xml deploy site -Dmaven.test.skip=true

env:
  global:
    - secure: HMQXoOOMq4371MSAI657ICq1NP+zlA0uz/koDt4q51ok8ouyLcTAabpO9He5XQP4dxT7CCrNouksz+mwC1q6orVHbWkKmSB7TLnpcF/1E1a1v7rJwujWR8xYgv3ILCcroTtA4J/3bfCZXceTRrynWatzcXFp2DIDSIJzUkWj78NpaByZzI2JA9MM/wFt9EosNrK/ITJDVgFsaNkxLEbERKclP8SKbyPeSRG2xwjWmPXgzNgKsIm1hWdrkNbygEAY5hzyC2aei/PZ0XkfHHbM2pLJV7Dw+dtBayr3DqPKROIjQDO0rq6ZDwWPy5ovnFZLyFvI5J2IyiqUB55TRUhyHsmIbbiKQPlWYQ+3lGQQ0nwsP0+CNBbmJ25w4h2+jNzNFhftiqQ7ViU64jNLAlSwEJLmIDE+DKw+7N1ZbtWZ6E964fYT5SvLQhGjezZlBqkbxDvrM/0iSuicEuPW8Px/rp0Zyw1ncJAcgJ66zfk/9HHW/k4ZcOkBsVBlnzOp1r9OKVBC6BtvOaYcl7k+zlRkIOgmVOA8dra3ekTcei0GrcxlEAqzWwSy3aHUJO4IYOYHW8YCLv+Xb/PiGqdlX+AxvxlqKQLQM5XO/TDO2BtvD3HjYksPS40EUb+T53Zzo4SjjyNVH+nKsV3tsONpWTvudjPty/D4zrpvc7+5HkOd5ks=
    - secure: hRvNQdcFJAmrQzrEPloVfOjgIBORTxlr8CA5tXSLtawVGOz6wMzg8J4fapA4MJLoUssOv7tyD9p+eO8RkKcreG4+zLYGrdA55Onu4l70W4dxEJzmMCQSRQ4Y6oEPZjqjrpofFoiHU2EtsO+S9mcWM5aW6LMXC1EWx6c3xJi3UrgS7MqidjJt1ixQ64UvuTPD1ga7CBEwxorvAyExkuSx2YyokSk6/wvmsEUxgJkxBTbYwbzSXlzbEtU3OIWqHtLAitQ8zzBPgVAkHnRsXB2KP/32eQn2GDiK+8lxhDy4XPJrUckKk0fYSVJT652MqDeHC5OiJiWNKo0P3Ly3IP5C+FQoZP1T8p7S9SgYEsxWmGteLd+OoFo31OpHcfMd5iIMmylLzPlw6CZ9saOha74odF5z0nBp4d/9HP2dwP1U9GlRgXu24wcgxB/Q+kjDH1JwWzIIxAL2nzj0h+Wt/cIq7D58kF5ePmJ1j/Y4UHZRXYIbA4rM2E/hLg+BkQFpkdpW5pc8v1wjljYVCEmQ19WDopnF/FyAjaanQp+vvoC5DNK88MioHvUXoJS9VCeOJVoO+2ACexYntgKyIVAAotTitBskQLtIGAiDZTSYKhfNk2WaSKu2veUDIHqn2Zaf19ASXF3tOwpW+vfsOgVQD4zgyGuiFiEDmeYh7nIAA2VESGQ=
    - secure: TrWwtko5ArIalYxjxt4uTBLG2LEwaRlEo49nF9POOllDOiLegZ91DrBnuas06eOo4FeRSbtepvJK2PWFYjjmsLi0nME/Nb5gS/x5kLTGNDZhYRnJA7R+fwBRA/68Mf1WSZG5dbDaUEJXAbZdb4TydUVGNkafGNkjkELI/wMgDR7++bdvrZJt8tB4lQAFMjn1/fU/jX+Gml0WcmPmUXtQe+c9YNICPMVcITR7DKyscpsp58icMfS+RUEbC2/l3cMC2X4wX+E4qdJmsKDMMO027BSFbs7Gu5LZgjCQHelHHeW2CD+q7SuWV4Nufj41uNuv3W8+yZ5muu53CWougXIxUqcsmXrK4fblY1cPG6u+vN+ZDrZc6SPtIiCEMPd+XcLxZxa15AHO1Wre4uooEGfyM4O9e/Q4RpiFwaRgOuIDwkD84H9S7EdJzKtdIwKwoKkY51W9KV9C9KfWCFjCJQQXrJBslPiXUiwNqQEFPodVC6rP1GfO2D5cSFFQtbPOWPgW8bUozb0CoSydiDFZo770qfNGpB0utgudNd/9QSIKpdzBX/I0F6G0zt76TVpjy8Nbr82BSBsKbbenB0XWywKqtT1JanJQQnzEldqe1ZBUBqGwg9yEqJ/9ECnBgEBWA4+aeX+tk3/AAzQchIeyMHlG0wk42HdWIAcwHKW2nTx7De8=