language: java

cache:
  directories:
  - $HOME/.m2

before_install:
  - pip install --user codecov

script:
  - mvn package site

after_success:
  - codecov

branches:
except:
  - gh-pages
