language: java

cache:
  directories:
  - "$HOME/.m2"

before_install:
  - pip install --user codecov

script:
  - mvn package deploy

after_success:
  - codecov

branches: 
  except:
    - gh-pages

env:
  global:
    - secure: GffQQCf6agVh9Jn+1GMceKsiSP/ESPz4KSkj+9AXEsRx5TSVOJKtSCPB8D3BERrWSGDbenjtWdjGoB504xvAPS0iXe/hOpE+YzwBndF7KeQV6Pw4cw1bbzaYVaHvn6hA6v/5WxtTDBXuHD1qb78qXUVKhCN9jP0O98fWow+6jQB+UwuoJoyVCkUAnR3A+v4SI/6IV6Ly4omvhUaCRsjcLlJ+upFCkHgzc5isiXtx6W/nXEoLN20eGdQq7FUNOuW7cM9gDKB6bKYVHAPj0GStU3HCVd5edDe83AhXVl0MHcqDbXB7M2ImfPt9CLH0ZLBvI5Y/SUU3IqodpU6mZRdZVB4N+IOmE6iLgRb1xDAvhrByCUL5zje6Ajc7nTv4H6skHD3JXOqBdBQbdIXSKV+DtGpbhZ5+cvl6AYl18ufC53k3d8GjcPXWZ7HNRAfvMPLs5hv07XU+4YTLQ8MN+hKA22RjKyae8U+ZRi5bv2e1tI5R4/P5BxjAtWa+g0gNp3v1PeSB4ClBGH7juh1URDBt/ALZAax5pRsWVlj3UPUnjNjzBWfVhMBPGSC799Jvc0u4oqrwMe8/AH6oEH8j1sfVWWf1yUuV85d6QeGm0rJzxgGEhciawZqM1a0VoyLe2bjEXy7CJB7vlkC3y79J1LBe79yvuKInqn8D7Xfl4Ln0Bxg=
    - secure: c5OILc8R3fjaeLTU4M94TTifi8pWNsZEGpthbofK1thcM89RL216qhUVqZiO1/Wro4CvZ84/TjHYQvLTprRtWRcT3J41AkcNyxh0xPycRb438R1NxArBwzktT9Jqgf+cYvMv6OC3Tb6VTlJgak7P4yN0XbW+xOQ3BmRSLz1BzghJgxPyfuC6qHHU0k1nig3RnKLlmqNyYs+kbLKEbREnwSJzcGsDdwS08KmxnUvL2kekksGlmQyMaYfmFE61OB+1c4/we/XLyY6TYkSGztIFUvL4Dos6hP2XLebOLkMeLhMB5vHMncuL6bb4fmlIdbaKLjoDCitedevk/PLMvnw5g5oySf/FNc6oduJDCvnLIspnkHko9uYLrGYM5cAttqfErBn1EI6mhwa2+Y3UDkjgYw+elEfmkOBI9uxB9ZcV5/5miWV/Xwk8aDYdnM2Yl09qzRtNn3iFqYfaPTu86w5VrolnK3iNVO99625hV7Mhd6K95K1jLjtKTc4yQ6aPga13h+lHtQmbWF3k+XlOmnH754IhP4WBKd4dK7+3gqxa7m8AfmqWlyIk5GKGTAiPWvUCu0UvzioEcgGRKR05RP5/9WSMY2I1nkLGi4jrJggXTRuDhxIzLiVC5gij5u8tEIy1JMwDIRgmRLyXjE5OpllvA2yTJ3DLOOy3SAgKFDpPUsQ=
    - secure: VruzliJ5pRHla6DsErxRpEyj3spuQpQXCF9cutjk501/WXQc/jxtYRxvCW3t4y19ydLDpy7ktCqPvRPlUqCCD1PZQsd43ulq5W/ahsN2lSyBX8iWso3oB6rJldtee6ZQm7EWM4HVsTQY8YnQ+q2LwgXMLWw8hfpRbScx5kBVmW6pj/qvpcvvY1/xPlXVtvykNhX5DQOyrlEqHok6QCc6hM5tSDTfcxXrsETLREJxfZa6NSZRr34rL1dl5V0GFovAuOGvjfS3jt4qtggphez94XWT7phO/9XRolkOVcimZrDKcqoI/Ap3GbbiumOWQ2juGeVFAgXMC9IMsRUqVUABLbEpiOr/wZaYUP+QblbG7EAntN3Qk3FgWAjCOtBQ19V7STx7SN5KuscvoGCgbf7w6Xp1wRTvJDSVBjD0gtRBBth5FX0NGypuRQAh1KuHqqsWyq+54ueL3Ne7SVLCvm3om9IWZPsKlI/uUSImtuzaZjWmLKmPzvl/ihHaKgjOBWtXJuQtE7BhbvdfIqaByq5455iPatTAKZu5Jg8lIGQXSN/78C5rCUIk5kR+e3M9XNOphkvIYENqVmV/Q+YaIsD95GUnV6FqIoLphhFiJs9DDHUMAJNqVsMP01qOyp64sgem/hKnGvUX3nY5bclSrU4psZAfYiK4lBVcUlgz9WjHig4=